# Hadolint Configuration for Dockerfiles
# Warnings as errors

# Ignore specific rules (if absolutely necessary)
ignored:
  - DL3008  # Pin versions in apt-get install (impractical for base system packages)

# Treat warnings as errors
failure-threshold: warning

# Strict mode
strict-labels: true
