name: Documentation Issue
description: Report missing or incorrect documentation
title: "[Docs]: "
labels: ["type: documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: component
    attributes:
      label: Documentation Area
      description: Which documentation needs attention?
      options:
        - API Documentation
        - User Guide
        - Developer Guide
        - Architecture Documentation
        - README files
        - Code Comments
        - LaTeX Documentation
        - Tutorial/Examples
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect/outdated information
        - Unclear explanation
        - Broken links
        - Formatting issues
        - Typos/grammar
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is the documentation issue?
      placeholder: |
        File path: /path/to/file.md
        Section: "Installation Guide"
        URL: https://...
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: What does the current documentation say (if applicable)?
      placeholder: Quote the current text or describe what's missing
      render: markdown

  - type: textarea
    id: suggested
    attributes:
      label: Suggested Improvement
      description: What should the documentation say instead?
      placeholder: Provide corrected text or describe what should be added
      render: markdown
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: |
        - Why is this confusing?
        - What were you trying to do?
        - Screenshots of the issue
