name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["type: feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this affect?
      options:
        - Frontend
        - Backend
        - Language Services
        - Babbage Engine
        - Curriculum
        - Documentation
        - Infrastructure
        - Cross-cutting
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - High (critical for project success)
        - Medium (nice to have, valuable)
        - Low (nice to have, not urgent)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or need this feature addresses
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would this feature work?
      placeholder: |
        Describe your proposed solution in detail:
        - What would it do?
        - How would users interact with it?
        - What would the API/interface look like?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you thought about?
      placeholder: Describe alternative solutions or workarounds

  - type: textarea
    id: examples
    attributes:
      label: Examples and Use Cases
      description: Provide examples of how this feature would be used
      placeholder: |
        Example use case 1:
        - User action...
        - Expected result...
        
        Example use case 2:
        - ...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups and References
      description: Add mockups, wireframes, or links to similar features
      placeholder: Drag and drop images or paste links here

  - type: checkboxes
    id: breaking
    attributes:
      label: Breaking Changes
      description: Would this require breaking changes?
      options:
        - label: This feature would require breaking changes to existing APIs
        - label: This feature is backward compatible

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Notes
      description: Technical details about how this could be implemented (optional)
      placeholder: |
        Any technical considerations:
        - Dependencies needed
        - API design
        - Database schema changes
        - Migration path

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: Add any other context about the feature request here
