
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'LPAREN NUMBER RPAREN STRING SYMBOLexpression : atomexpression : LPAREN elements RPARENelements : elements expressionelements :atom : SYMBOLatom : NUMBERatom : STRING'
    
_lr_action_items = {'LPAREN':([0,2,3,4,5,6,7,8,9,],[3,-1,-4,-5,-6,-7,3,-2,-3,]),'SYMBOL':([0,2,3,4,5,6,7,8,9,],[4,-1,-4,-5,-6,-7,4,-2,-3,]),'NUMBER':([0,2,3,4,5,6,7,8,9,],[5,-1,-4,-5,-6,-7,5,-2,-3,]),'STRING':([0,2,3,4,5,6,7,8,9,],[6,-1,-4,-5,-6,-7,6,-2,-3,]),'$end':([1,2,4,5,6,8,],[0,-1,-5,-6,-7,-2,]),'RPAREN':([2,3,4,5,6,7,8,9,],[-1,-4,-5,-6,-7,8,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,7,],[1,9,]),'atom':([0,7,],[2,2,]),'elements':([3,],[7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> atom','expression',1,'p_expression_atom','lisp_parser.py',9),
  ('expression -> LPAREN elements RPAREN','expression',3,'p_expression_sexpression','lisp_parser.py',13),
  ('elements -> elements expression','elements',2,'p_elements_list','lisp_parser.py',17),
  ('elements -> <empty>','elements',0,'p_elements_empty','lisp_parser.py',21),
  ('atom -> SYMBOL','atom',1,'p_atom_symbol','lisp_parser.py',25),
  ('atom -> NUMBER','atom',1,'p_atom_number','lisp_parser.py',29),
  ('atom -> STRING','atom',1,'p_atom_string','lisp_parser.py',33),
]
