"""initial schema

Revision ID: aeff3d1c3894
Revises: 
Create Date: 2026-02-26 01:30:51.380272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeff3d1c3894'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('historical_context', sa.Text(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eras_id'), 'eras', ['id'], unique=False)
    op.create_index(op.f('ix_eras_label'), 'eras', ['label'], unique=True)
    op.create_index(op.f('ix_eras_order'), 'eras', ['order'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('era_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('era_enum', sa.Enum('PREHISTORY', 'ANCIENT', 'MEDIEVAL', 'EARLY_MODERN', 'MODERN', 'CONTEMPORARY', name='moduleera'), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('prerequisites', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['era_id'], ['eras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_era_enum'), 'modules', ['era_enum'], unique=False)
    op.create_index(op.f('ix_modules_era_id'), 'modules', ['era_id'], unique=False)
    op.create_index(op.f('ix_modules_id'), 'modules', ['id'], unique=False)
    op.create_index(op.f('ix_modules_sequence_order'), 'modules', ['sequence_order'], unique=False)
    op.create_index(op.f('ix_modules_slug'), 'modules', ['slug'], unique=True)
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('languages_supported', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficultylevel'), nullable=False),
    sa.Column('starter_code', sa.JSON(), nullable=True),
    sa.Column('solution_code', sa.JSON(), nullable=True),
    sa.Column('test_cases', sa.JSON(), nullable=False),
    sa.Column('hints', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('memory_limit_mb', sa.Integer(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    op.create_index(op.f('ix_exercises_module_id'), 'exercises', ['module_id'], unique=False)
    op.create_index(op.f('ix_exercises_slug'), 'exercises', ['slug'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('lesson_type', sa.Enum('READING', 'INTERACTIVE', 'CODING', 'QUIZ', 'SYNTHESIS', name='lessontype'), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('language', sa.Enum('C', 'PYTHON', 'HASKELL', 'IDRIS2', 'LISP', 'ASSEMBLY', 'JAVA', 'SYSTEMF', name='supportedlanguage'), nullable=True),
    sa.Column('starter_code', sa.Text(), nullable=True),
    sa.Column('solution_code', sa.Text(), nullable=True),
    sa.Column('test_cases', sa.JSON(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    op.create_index(op.f('ix_lessons_lesson_type'), 'lessons', ['lesson_type'], unique=False)
    op.create_index(op.f('ix_lessons_module_id'), 'lessons', ['module_id'], unique=False)
    op.create_index(op.f('ix_lessons_slug'), 'lessons', ['slug'], unique=False)
    op.create_table('module_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lessons_completed', sa.Integer(), nullable=False),
    sa.Column('total_lessons', sa.Integer(), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_progress_id'), 'module_progress', ['id'], unique=False)
    op.create_index(op.f('ix_module_progress_module_id'), 'module_progress', ['module_id'], unique=False)
    op.create_index(op.f('ix_module_progress_user_id'), 'module_progress', ['user_id'], unique=False)
    op.create_table('code_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('submitted_code', sa.Text(), nullable=False),
    sa.Column('language', sa.Enum('C', 'PYTHON', 'HASKELL', 'IDRIS2', 'LISP', 'ASSEMBLY', 'JAVA', 'SYSTEMF', name='supportedlanguage'), nullable=False),
    sa.Column('passed_tests', sa.Integer(), nullable=False),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('execution_output', sa.Text(), nullable=True),
    sa.Column('execution_error', sa.Text(), nullable=True),
    sa.Column('is_successful', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_submissions_id'), 'code_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_code_submissions_lesson_id'), 'code_submissions', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_code_submissions_user_id'), 'code_submissions', ['user_id'], unique=False)
    op.create_table('exercise_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('best_score', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_submitted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_progress_exercise_id'), 'exercise_progress', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_progress_id'), 'exercise_progress', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_progress_user_id'), 'exercise_progress', ['user_id'], unique=False)
    op.create_table('exercise_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('submitted_code', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('passed_tests', sa.Integer(), nullable=False),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('score_percentage', sa.Integer(), nullable=True),
    sa.Column('execution_output', sa.Text(), nullable=True),
    sa.Column('execution_error', sa.Text(), nullable=True),
    sa.Column('is_successful', sa.Boolean(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('memory_used_mb', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_submissions_exercise_id'), 'exercise_submissions', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_submissions_id'), 'exercise_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_submissions_user_id'), 'exercise_submissions', ['user_id'], unique=False)
    op.create_table('lesson_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_progress_id'), 'lesson_progress', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_progress_lesson_id'), 'lesson_progress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_progress_user_id'), 'lesson_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_progress_user_id'), table_name='lesson_progress')
    op.drop_index(op.f('ix_lesson_progress_lesson_id'), table_name='lesson_progress')
    op.drop_index(op.f('ix_lesson_progress_id'), table_name='lesson_progress')
    op.drop_table('lesson_progress')
    op.drop_index(op.f('ix_exercise_submissions_user_id'), table_name='exercise_submissions')
    op.drop_index(op.f('ix_exercise_submissions_id'), table_name='exercise_submissions')
    op.drop_index(op.f('ix_exercise_submissions_exercise_id'), table_name='exercise_submissions')
    op.drop_table('exercise_submissions')
    op.drop_index(op.f('ix_exercise_progress_user_id'), table_name='exercise_progress')
    op.drop_index(op.f('ix_exercise_progress_id'), table_name='exercise_progress')
    op.drop_index(op.f('ix_exercise_progress_exercise_id'), table_name='exercise_progress')
    op.drop_table('exercise_progress')
    op.drop_index(op.f('ix_code_submissions_user_id'), table_name='code_submissions')
    op.drop_index(op.f('ix_code_submissions_lesson_id'), table_name='code_submissions')
    op.drop_index(op.f('ix_code_submissions_id'), table_name='code_submissions')
    op.drop_table('code_submissions')
    op.drop_index(op.f('ix_module_progress_user_id'), table_name='module_progress')
    op.drop_index(op.f('ix_module_progress_module_id'), table_name='module_progress')
    op.drop_index(op.f('ix_module_progress_id'), table_name='module_progress')
    op.drop_table('module_progress')
    op.drop_index(op.f('ix_lessons_slug'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_module_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_lesson_type'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_exercises_slug'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_module_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_modules_slug'), table_name='modules')
    op.drop_index(op.f('ix_modules_sequence_order'), table_name='modules')
    op.drop_index(op.f('ix_modules_id'), table_name='modules')
    op.drop_index(op.f('ix_modules_era_id'), table_name='modules')
    op.drop_index(op.f('ix_modules_era_enum'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_eras_order'), table_name='eras')
    op.drop_index(op.f('ix_eras_label'), table_name='eras')
    op.drop_index(op.f('ix_eras_id'), table_name='eras')
    op.drop_table('eras')
    # ### end Alembic commands ###
