# ============================================================================
# PATH MAPPING SED SCRIPT FOR LINK UPDATES
# ============================================================================
# This script updates all old file paths to new directory structure
# Format: s|old_pattern|new_pattern|g

# ============================================================================
# SECTION 1: Root-level files moving to DEVELOPMENT_GUIDES
# ============================================================================
s|../BUILD\.md|../DEVELOPMENT_GUIDES/BUILD.md|g
s|BUILD\.md|DEVELOPMENT_GUIDES/BUILD.md|g

s|../LANGUAGE_SERVICE_SPECIFICATION\.md|../DEVELOPMENT_GUIDES/LANGUAGE_SERVICE_SPECIFICATION.md|g
s|LANGUAGE_SERVICE_SPECIFICATION\.md|DEVELOPMENT_GUIDES/LANGUAGE_SERVICE_SPECIFICATION.md|g

s|../WEEK_1_CHECKLIST\.md|../DEVELOPMENT_GUIDES/WEEK_1_CHECKLIST.md|g
s|WEEK_1_CHECKLIST\.md|DEVELOPMENT_GUIDES/WEEK_1_CHECKLIST.md|g

s|../WEEK_2_IMPLEMENTATION_PLAN\.md|../DEVELOPMENT_GUIDES/WEEK_2_IMPLEMENTATION_PLAN.md|g
s|WEEK_2_IMPLEMENTATION_PLAN\.md|DEVELOPMENT_GUIDES/WEEK_2_IMPLEMENTATION_PLAN.md|g

s|../SECURITY_LAYERS_IMPLEMENTATION\.md|../DEVELOPMENT_GUIDES/SECURITY_LAYERS_IMPLEMENTATION.md|g
s|SECURITY_LAYERS_IMPLEMENTATION\.md|DEVELOPMENT_GUIDES/SECURITY_LAYERS_IMPLEMENTATION.md|g

# ============================================================================
# SECTION 2: Root-level files moving to ARCHITECTURE_AND_DESIGN
# ============================================================================
s|../ARCHITECTURE\.md|../ARCHITECTURE_AND_DESIGN/ARCHITECTURE.md|g
s|\[ARCHITECTURE\.md\](ARCHITECTURE\.md)|[ARCHITECTURE.md](../ARCHITECTURE_AND_DESIGN/ARCHITECTURE.md)|g
s|ARCHITECTURE\.md|ARCHITECTURE_AND_DESIGN/ARCHITECTURE.md|g

s|../IMPLEMENTATION_ROADMAP\.md|../ARCHITECTURE_AND_DESIGN/IMPLEMENTATION_ROADMAP.md|g
s|IMPLEMENTATION_ROADMAP\.md|ARCHITECTURE_AND_DESIGN/IMPLEMENTATION_ROADMAP.md|g

s|../LANGUAGE_SERVICES_ARCHITECTURE\.md|../ARCHITECTURE_AND_DESIGN/LANGUAGE_SERVICES_ARCHITECTURE.md|g
s|LANGUAGE_SERVICES_ARCHITECTURE\.md|ARCHITECTURE_AND_DESIGN/LANGUAGE_SERVICES_ARCHITECTURE.md|g

s|../PROJECT_STRUCTURE\.md|../ARCHITECTURE_AND_DESIGN/PROJECT_STRUCTURE.md|g
s|PROJECT_STRUCTURE\.md|ARCHITECTURE_AND_DESIGN/PROJECT_STRUCTURE.md|g

s|../STRATEGIC_ROADMAP\.md|../ARCHITECTURE_AND_DESIGN/STRATEGIC_ROADMAP.md|g
s|STRATEGIC_ROADMAP\.md|ARCHITECTURE_AND_DESIGN/STRATEGIC_ROADMAP.md|g

# ============================================================================
# SECTION 3: Root-level files moving to CURRICULUM_AND_CONTENT
# ============================================================================
s|../TYPE_THEORY_CURRICULUM\.md|../CURRICULUM_AND_CONTENT/TYPE_THEORY_CURRICULUM.md|g
s|TYPE_THEORY_CURRICULUM\.md|CURRICULUM_AND_CONTENT/TYPE_THEORY_CURRICULUM.md|g

s|../CONTENT_SCHEMA_DESIGN\.md|../CURRICULUM_AND_CONTENT/CONTENT_SCHEMA_DESIGN.md|g
s|CONTENT_SCHEMA_DESIGN\.md|CURRICULUM_AND_CONTENT/CONTENT_SCHEMA_DESIGN.md|g

s|../PEDAGOGICAL_WHITEPAPER_COMPLETION_SUMMARY\.md|../CURRICULUM_AND_CONTENT/PEDAGOGICAL_WHITEPAPER_COMPLETION_SUMMARY.md|g
s|PEDAGOGICAL_WHITEPAPER_COMPLETION_SUMMARY\.md|CURRICULUM_AND_CONTENT/PEDAGOGICAL_WHITEPAPER_COMPLETION_SUMMARY.md|g

# ============================================================================
# SECTION 4: /docs/ directory files (various destinations)
# ============================================================================
s|../../docs/EDUCATIONAL_CURRICULUM_MATERIALS\.md|../CURRICULUM_AND_CONTENT/EDUCATIONAL_CURRICULUM_MATERIALS.md|g
s|docs/EDUCATIONAL_CURRICULUM_MATERIALS\.md|CURRICULUM_AND_CONTENT/EDUCATIONAL_CURRICULUM_MATERIALS.md|g

s|../../docs/OPTIMAL_BABBAGE_SPECIFICATION\.md|../BABBAGE_ANALYTICAL_ENGINE/OPTIMAL_BABBAGE_SPECIFICATION.md|g
s|docs/OPTIMAL_BABBAGE_SPECIFICATION\.md|BABBAGE_ANALYTICAL_ENGINE/OPTIMAL_BABBAGE_SPECIFICATION.md|g

s|../../docs/SUPPLY_CHAIN_PROCUREMENT_GUIDE\.md|../BABBAGE_ANALYTICAL_ENGINE/SUPPLY_CHAIN_PROCUREMENT_GUIDE.md|g
s|docs/SUPPLY_CHAIN_PROCUREMENT_GUIDE\.md|BABBAGE_ANALYTICAL_ENGINE/SUPPLY_CHAIN_PROCUREMENT_GUIDE.md|g

s|../../docs/OPERATIONS_AND_MAINTENANCE\.md|../BABBAGE_ANALYTICAL_ENGINE/OPERATIONS_AND_MAINTENANCE.md|g
s|docs/OPERATIONS_AND_MAINTENANCE\.md|BABBAGE_ANALYTICAL_ENGINE/OPERATIONS_AND_MAINTENANCE.md|g

s|../../docs/EMULATOR_SPECIFICATION\.md|../BABBAGE_ANALYTICAL_ENGINE/EMULATOR_SPECIFICATION.md|g
s|docs/EMULATOR_SPECIFICATION\.md|BABBAGE_ANALYTICAL_ENGINE/EMULATOR_SPECIFICATION.md|g

s|../../docs/EMULATOR_USER_GUIDE\.md|../BABBAGE_ANALYTICAL_ENGINE/EMULATOR_USER_GUIDE.md|g
s|docs/EMULATOR_USER_GUIDE\.md|BABBAGE_ANALYTICAL_ENGINE/EMULATOR_USER_GUIDE.md|g

s|../../docs/ASSEMBLY_INSTRUCTIONS_PART1\.md|../BABBAGE_ANALYTICAL_ENGINE/ASSEMBLY_INSTRUCTIONS_PART1.md|g
s|docs/ASSEMBLY_INSTRUCTIONS_PART1\.md|BABBAGE_ANALYTICAL_ENGINE/ASSEMBLY_INSTRUCTIONS_PART1.md|g

s|../../docs/ECONOMIC_MODELS_MASS_PRODUCTION\.md|../BABBAGE_ANALYTICAL_ENGINE/ECONOMIC_MODELS_MASS_PRODUCTION.md|g
s|docs/ECONOMIC_MODELS_MASS_PRODUCTION\.md|BABBAGE_ANALYTICAL_ENGINE/ECONOMIC_MODELS_MASS_PRODUCTION.md|g

s|../../docs/BABBAGE_README\.md|../BABBAGE_ANALYTICAL_ENGINE/BABBAGE_README.md|g
s|docs/BABBAGE_README\.md|BABBAGE_ANALYTICAL_ENGINE/BABBAGE_README.md|g

s|../../docs/BABBAGE_PROJECT_SUMMARY\.md|../BABBAGE_ANALYTICAL_ENGINE/BABBAGE_PROJECT_SUMMARY.md|g
s|docs/BABBAGE_PROJECT_SUMMARY\.md|BABBAGE_ANALYTICAL_ENGINE/BABBAGE_PROJECT_SUMMARY.md|g

s|../../docs/BABBAGE_CRITICAL_REVIEW\.md|../BABBAGE_ANALYTICAL_ENGINE/BABBAGE_CRITICAL_REVIEW.md|g
s|docs/BABBAGE_CRITICAL_REVIEW\.md|BABBAGE_ANALYTICAL_ENGINE/BABBAGE_CRITICAL_REVIEW.md|g

s|../../docs/HISTORICAL_AUDIT_AND_CORRECTIONS\.md|../HISTORICAL_CONTEXT/HISTORICAL_AUDIT_AND_CORRECTIONS.md|g
s|docs/HISTORICAL_AUDIT_AND_CORRECTIONS\.md|HISTORICAL_CONTEXT/HISTORICAL_AUDIT_AND_CORRECTIONS.md|g

s|../../docs/HISTORICAL_FICTION_NARRATIVES\.md|../HISTORICAL_CONTEXT/HISTORICAL_FICTION_NARRATIVES.md|g
s|docs/HISTORICAL_FICTION_NARRATIVES\.md|HISTORICAL_CONTEXT/HISTORICAL_FICTION_NARRATIVES.md|g

s|../../docs/EXAMPLE_PROGRAMS\.md|../CURRICULUM_AND_CONTENT/EXAMPLE_PROGRAMS.md|g
s|docs/EXAMPLE_PROGRAMS\.md|CURRICULUM_AND_CONTENT/EXAMPLE_PROGRAMS.md|g

# ============================================================================
# SECTION 5: /infrastructure/ directory files
# ============================================================================
s|../../infrastructure/INFRASTRUCTURE_STRATEGY\.md|../INFRASTRUCTURE_AND_DEPLOYMENT/INFRASTRUCTURE_STRATEGY.md|g
s|infrastructure/INFRASTRUCTURE_STRATEGY\.md|INFRASTRUCTURE_AND_DEPLOYMENT/INFRASTRUCTURE_STRATEGY.md|g

s|../../infrastructure/BSD_INTEGRATION_SPEC\.md|../INFRASTRUCTURE_AND_DEPLOYMENT/BSD_INTEGRATION_SPEC.md|g
s|infrastructure/BSD_INTEGRATION_SPEC\.md|INFRASTRUCTURE_AND_DEPLOYMENT/BSD_INTEGRATION_SPEC.md|g

# ============================================================================
# SECTION 6: Root-level files moving to INFRASTRUCTURE_AND_DEPLOYMENT
# ============================================================================
s|../DOCKER_INFRASTRUCTURE\.md|../INFRASTRUCTURE_AND_DEPLOYMENT/DOCKER_INFRASTRUCTURE.md|g
s|DOCKER_INFRASTRUCTURE\.md|INFRASTRUCTURE_AND_DEPLOYMENT/DOCKER_INFRASTRUCTURE.md|g

# ============================================================================
# SECTION 7: /phase3/ and /phase4/ directory files
# ============================================================================
s|../../phase3/\([^)]*\.md\)|../IMPLEMENTATION_PHASES/PHASE_3/\1|g
s|phase3/\([^)]*\.md\)|IMPLEMENTATION_PHASES/PHASE_3/\1|g

s|../../phase4/\([^)]*\.md\)|../IMPLEMENTATION_PHASES/PHASE_4/\1|g
s|phase4/\([^)]*\.md\)|IMPLEMENTATION_PHASES/PHASE_4/\1|g

# ============================================================================
# SECTION 8: /whitepaper/ directory files
# ============================================================================
s|../../whitepaper/WHITEPAPER_DELIVERY_SUMMARY\.md|../BABBAGE_ANALYTICAL_ENGINE/whitepaper/WHITEPAPER_DELIVERY_SUMMARY.md|g
s|whitepaper/WHITEPAPER_DELIVERY_SUMMARY\.md|BABBAGE_ANALYTICAL_ENGINE/whitepaper/WHITEPAPER_DELIVERY_SUMMARY.md|g

s|../../whitepaper/MANUFACTURING_THIRD_WORLD\.md|../BABBAGE_ANALYTICAL_ENGINE/whitepaper/MANUFACTURING_THIRD_WORLD.md|g
s|whitepaper/MANUFACTURING_THIRD_WORLD\.md|BABBAGE_ANALYTICAL_ENGINE/whitepaper/MANUFACTURING_THIRD_WORLD.md|g

s|../../whitepaper/COMPILATION\.md|../BABBAGE_ANALYTICAL_ENGINE/whitepaper/COMPILATION.md|g
s|whitepaper/COMPILATION\.md|BABBAGE_ANALYTICAL_ENGINE/whitepaper/COMPILATION.md|g

# ============================================================================
# SECTION 9: Root-level phase files
# ============================================================================
s|../PHASE2_COMPLETION_INDEX\.md|../IMPLEMENTATION_PHASES/PHASE2_COMPLETION_INDEX.md|g
s|PHASE2_COMPLETION_INDEX\.md|IMPLEMENTATION_PHASES/PHASE2_COMPLETION_INDEX.md|g

s|../BUILD_INFRASTRUCTURE_COMPLETION_SUMMARY\.md|../IMPLEMENTATION_PHASES/BUILD_INFRASTRUCTURE_COMPLETION_SUMMARY.md|g
s|BUILD_INFRASTRUCTURE_COMPLETION_SUMMARY\.md|IMPLEMENTATION_PHASES/BUILD_INFRASTRUCTURE_COMPLETION_SUMMARY.md|g

# ============================================================================
# SECTION 10: Root-level timeline files
# ============================================================================
s|../TIMELINE_VISUALIZATION\.md|../HISTORICAL_CONTEXT/TIMELINE_VISUALIZATION.md|g
s|TIMELINE_VISUALIZATION\.md|HISTORICAL_CONTEXT/TIMELINE_VISUALIZATION.md|g

s|../TIMELINE_VISUALIZATION_SPEC\.md|../HISTORICAL_CONTEXT/TIMELINE_VISUALIZATION_SPEC.md|g
s|TIMELINE_VISUALIZATION_SPEC\.md|HISTORICAL_CONTEXT/TIMELINE_VISUALIZATION_SPEC.md|g

# ============================================================================
# SECTION 11: Legacy and archived files
# ============================================================================
s|../MVP_FILE_STRUCTURE\.md|../ARCHIVED_AND_LEGACY/MVP_FILE_STRUCTURE.md|g
s|MVP_FILE_STRUCTURE\.md|ARCHIVED_AND_LEGACY/MVP_FILE_STRUCTURE.md|g

s|../README_OUTPUT\.md|../ARCHIVED_AND_LEGACY/README_OUTPUT.md|g
s|README_OUTPUT\.md|ARCHIVED_AND_LEGACY/README_OUTPUT.md|g

